### ISSUE TITLE
change navigation bar text color to black and hide bot name in received message

### ISSUE THREAD

**Issue by mohamed-ikram** [Kommunicate-io/Kommunicate-React-Native-Sample#1]
i have already added applozic-settings.json in asset folder in android how to change the navigation bar text to black color and hide bot name in received message

**Comment by harishbala1o** [comment]
@mohamed-ikram The navigation bar colour is changed from dashboard setting only as of now. It cannot be changed from applozic-settings.json file. Currently, we do not have a setting to hide bot name

**Comment by mohamed-ikram** [comment]
Actually I need the hide the bot name in receive message not in the
navigation bar is it possible to hide

**Comment by harishbala1o** [comment]
Hello, @mohamed-ikram  sorry for the delayed reply, To hide the bot name in message part is in our roadmap. we will notify you once implemented

**Comment by mohamed-ikram** [comment]
@harishbala1o okay thanks
